### ISSUE TITLE
集成到 vs2013 cordova项目，无法编译通过

### ISSUE THREAD

**Issue by chenair** [south-pacific/cordova-plugin-updateapp#4]
我把插件集成进来后，编译直接报错，是否插件本身存在问题？或者你的文档有遗漏之处？麻烦帮忙看看，非常感谢。

**Comment by south-pacific** [comment]
报的是什么错呢？
我猜测应该是R.java资源文件报错，这个需要你手动修改下该文件的路径：import xxx.xxx.xxx.R;
